# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    app.mailer.mailer:
        class: AppBundle\Mailer\Mailer
        arguments: ['@swiftmailer.mailer', '@templating', '@router', '%mailer_user%']
    app.subscriber.data_modified:
        class: AppBundle\EventListener\DataModifiedSubscriber
        arguments: ['@app.mailer.mailer']
        tags:
            - { name: kernel.event_subscriber }
